"""Render the 115 report cards of the Video-Index paper (Appendix X) to transparent PNGs for the post.

Each card (figs/report_cards/<name>.pdf, 396 x 126 pt, generated by figs/scripts/fig_report_card.py) is
rasterized at 260 dpi, its white background turned into alpha by the rule of render_paper_figures.py, and
stored as a 256-colour palette PNG, about 20 KB a card. The file name is export_appendix.slug(name).

Usage: python3 render_report_cards.py <paper repo>
Output: ../cards/<slug>.png, 1430 x 455 px.
"""
import re
import sys
from pathlib import Path

import numpy as np
import pymupdf as fitz
from PIL import Image

from render_paper_figures import white_to_alpha

REPO = Path(sys.argv[1] if len(sys.argv) > 1 else Path.home() / 'Downloads/apex_paper').resolve()
OUT = Path(__file__).resolve().parent.parent / 'cards'


def slug(name):
    return re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')


def main():
    OUT.mkdir(exist_ok=True)
    names = re.findall(r'report_cards/([^}]*)\.pdf', (REPO / 'figs' / 'report_cards.tex').read_text(encoding='utf-8'))
    assert len(names) == 115 and len({slug(n) for n in names}) == 115, len(names)
    total = 0
    for name in names:
        page = fitz.open(REPO / 'figs' / 'report_cards' / (name + '.pdf'))[0]
        assert abs(page.rect.width - 396) < 0.5 and abs(page.rect.height - 126) < 0.5, (name, page.rect)
        pm = page.get_pixmap(dpi=260, alpha=False)
        rgb = np.frombuffer(pm.samples, dtype=np.uint8).reshape(pm.height, pm.width, pm.n)[:, :, :3] / 255.0
        img = Image.fromarray((white_to_alpha(rgb) * 255 + 0.5).astype(np.uint8), 'RGBA')
        path = OUT / (slug(name) + '.png')
        img.quantize(colors=256, method=Image.Quantize.FASTOCTREE).save(path, optimize=True)
        total += path.stat().st_size
    print(f'wrote {len(names)} cards to {OUT}, {total / 1e6:.1f} MB')


if __name__ == '__main__':
    main()
